### ISSUE TITLE
ArgumentError in Devise::Registrations#create

### ISSUE THREAD

**Issue by nicobobb** [thanhluanuit/instuigram#1]
I create a user and the following error appears:

Showing /home/nico/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/devise-4.5.0/app/views/devise/mailer/confirmation_instructions.html.erb where line #5 raised:

Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true

**Comment by thanhluanuit** [comment]
Hi @nicobobb, thanks for your feedback.

You can fix this errors by add below code to config/environments/development.rb:

`config.action_mailer.default_url_options = { :host => 'localhost', :port => 3000 }`

But now, I temporary remove :confirmable module of Devise in User model (app/models/user.rb), please pull code to see new update.

I'll add :confirmable module back to User model in next part.

Thanks!
